[package]
name = "v8worker"
version = "0.1.0"
authors = ["tempbottle <tempbottle@gmail.com>"]

[dependencies]
libc = "0.2"
bytes = "0.4"

[build-dependencies]
cc = "1"


[dev-dependencies]
env_logger = "0.5"
lazy_static = "1.0"
parking_lot = "0.6"